{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"../Base/images/liga logo.png\" width=\"500\"/>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"../Base/images/python logo.png\" width=\"165\"/>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    " # Курс \"Основы программирования на Python\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Исключения\n",
    "\n",
    "Исключения возникают тогда, когда в программе возникает некоторая исключительная ситуация. Например, к чему приведёт попытка чтения несуществующего файла? Или если файл был случайно удалён, пока программа работала? Такие ситуации обрабатываются при помощи исключений. Это касается и программ, содержащих недействительные команды. В этом случае Python\n",
    "поднимает руки и сообщает, что обнаружил ошибку.\n",
    "\n",
    "```\n",
    "\n",
    "```\n",
    "\n",
    "### 9.1 Ошибки\n",
    "Рассмотрим простой вызов функции print. Что, если мы ошибочно напишем print как Print? Обратите внимание на заглавную букву. В этом случае Python поднимает синтаксическую ошибку."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Print' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-6084d3919f80>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mPrint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Привет, Мир!'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'Print' is not defined"
     ]
    }
   ],
   "source": [
    "Print('Привет, Мир!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Привет, Мир!\n"
     ]
    }
   ],
   "source": [
    "print('Привет, Мир!')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Обратите внимание, что была поднята ошибка `NameError`, а также указано место, где была обнаружена ошибка. Так в данном случае действует обработчик ошибок.\n",
    "\n",
    "```\n",
    "\n",
    "```\n",
    "\n",
    "### 9.2 Исключения\n",
    "Попытаемся считать что-либо от пользователя. Нажмите Сtrl-D (или Ctrl+Z в Windows) и посмотрите, что произойдёт."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите что-нибудь --> 513651\n"
     ]
    }
   ],
   "source": [
    "s = input('Введите что-нибудь --> ')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 9.3 Обработка исключений\n",
    "\n",
    "Обрабатывать исключения можно при помощи оператора `try..except1`. При этом все обычные команды помещаются внутрь `try-блока`, а все обработчики исключений – в `except-блок`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите что-нибудь --> 5555wwwww\n",
      "Вы ввели 5555wwwww\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    text = input('Введите что-нибудь --> ')\n",
    "except EOFError:\n",
    "    print('Ну зачем вы сделали мне EOF?')\n",
    "except KeyboardInterrupt:\n",
    "    print('Вы отменили операцию.')\n",
    "else:\n",
    "    print('Вы ввели {0}'.format(text))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Здесь мы поместили все команды, которые могут вызвать исключения/ошибки, внутрь блока `try`, а затем поместили обработчики соответствующих ошибок/исключений в блок except. Выражение except может обрабатывать как одиночную ошибку или исключение, так и список ошибок/исключений в скобках. Если не указано имя ошибки или исключения, обрабатываться будут все ошибки и исключения.\n",
    "\n",
    "Помните, что для каждого выражения `try` должно быть хотя бы одно соответствующее выражение except. Иначе какой смысл был бы в блоке `try`?\n",
    "\n",
    "Если ошибка или исключение не обработано, будет вызван обработчик Python по умолчанию, который останавливает выполнение программы и выводит на экран сообщение об ошибке. Выше мы уже видели это в действии.\n",
    "\n",
    "Можно также добавить пункт `else` к соответствующему блоку `try..except`. Этот пункт будет выполнен тогда, когда исключений не возникает.\n",
    "\n",
    "В следующем примере мы увидим, как можно получить объект исключения для дальнейшей работы с ним.\n",
    "\n",
    "```\n",
    "\n",
    "```\n",
    "### 9.4 Вызов исключения\n",
    "\n",
    "Исключение можно поднять при помощи оператора `raise2`, передав ему имя ошибки/исключения, а также объект исключения, который нужно выбросить. Вызываемая ошибка или исключение должна быть классом, который прямо или непрямо является производным от класса `Exception`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите что-нибудь --> dffe\n",
      "Не было исключений.\n"
     ]
    }
   ],
   "source": [
    "class ShortInputException(Exception):\n",
    "    '''Пользовательский класс исключения.'''\n",
    "    def __init__(self, length, atleast):\n",
    "        Exception.__init__(self)\n",
    "        self.length = length\n",
    "        self.atleast = atleast\n",
    "try:\n",
    "    text = input('Введите что-нибудь --> ')\n",
    "    if len(text) < 3:\n",
    "        raise ShortInputException(len(text), 3)\n",
    "    # Здесь может происходить обычная работа\n",
    "except EOFError:\n",
    "    print('Ну зачем вы сделали мне EOF?')\n",
    "except ShortInputException as ex:\n",
    "    print('ShortInputException: Длина введённой строки -- {0}; \\\n",
    "           ожидалось, как минимум, {1}'.format(ex.length, ex.atleast))\n",
    "else:\n",
    "    print('Не было исключений.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Здесь мы создаём наш собственный тип исключения. Этот новый тип исключения называется `ShortInputException`. Он содержит два поля: `length`, хранящее длину введённого текста, и atleast, указывающее, какую минимальную длину текста ожидала программа.\n",
    "В пункте `except` мы указываем класс ошибки `ShortInputException`, который будет сохранён как переменная `ex`, содержащая соответствующий объект ошибки/исключения. Это аналогично параметрам и аргументам при вызове функции. Внутри этого пункта except мы используем поля length и atleast объекта исключения для вывода необходимых сообщений пользователю.\n",
    "\n",
    "```\n",
    "\n",
    "```\n",
    "### 9.5 Try ... Finally\n",
    "Представим, что в программе происходит чтение файла и необходимо убедиться, что объект файла был корректно закрыт и что не возникло никакого исключения. Этого можно достичь с применением блока `finally`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "РџСЂРѕРіСЂР°РјРјРёСЂРѕРІР°С‚СЊ РІРµСЃРµР»Рѕ.\n",
      "Р•СЃР»Рё СЂР°Р±РѕС‚Р° СЃРєСѓС‡РЅР°,\n",
      "Р§С‚РѕР±С‹ РїСЂРёРґР°С‚СЊ РµР№ РІРµСЃС‘Р»С‹Р№ С‚РѕРЅ -\n",
      "РёСЃРїРѕР»СЊР·СѓР№ Python!(Очистка: Закрытие файла)\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "try:\n",
    "    f = open('poem.txt')\n",
    "    while True: # наш обычный способ читать файлы\n",
    "        line = f.readline()\n",
    "        if len(line) == 0:\n",
    "            break\n",
    "        print(line, end='')\n",
    "        time.sleep(2) # Пусть подождёт некоторое время\n",
    "except KeyboardInterrupt:\n",
    "    print('!! Вы отменили чтение файла.')\n",
    "finally:\n",
    "    f.close()\n",
    "    print('(Очистка: Закрытие файла)')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Здесь мы производим обычные операции чтения из файла, но в данном случае добавляем двухсекундный сон после вывода каждой строки при помощи функции `time.sleep`, чтобы программа выполнялась медленно (ведь Python очень быстр от природы). Во время выполнения программы нажмите `ctrl-c`, чтобы прервать/отменить выполнение программы.\n",
    "\n",
    "Пронаблюдайте, как при этом выдаётся исключение `KeyboardInterrupt`, и программа выходит. Однако, прежде чем программа \n",
    "выйдет, выполняется пункт `finally`, и файловый объект будет всегда закрыт.\n",
    "```\n",
    "\n",
    "```\n",
    "### 9.6 Оператор with\n",
    "Типичной схемой является запрос некоторого ресурса в блоке try с последующим освобождением этого ресурса в блоке `finally`. Для того, чтобы сделать это более «чисто», существует оператор `with4`:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "РџСЂРѕРіСЂР°РјРјРёСЂРѕРІР°С‚СЊ РІРµСЃРµР»Рѕ.\n",
      "Р•СЃР»Рё СЂР°Р±РѕС‚Р° СЃРєСѓС‡РЅР°,\n",
      "Р§С‚РѕР±С‹ РїСЂРёРґР°С‚СЊ РµР№ РІРµСЃС‘Р»С‹Р№ С‚РѕРЅ -\n",
      "РёСЃРїРѕР»СЊР·СѓР№ Python!"
     ]
    }
   ],
   "source": [
    "with open(\"poem.txt\") as f:\n",
    "    for line in f:\n",
    "        print(line, end='')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Вывод должен быть таким же, как и в предыдущем примере. Разница лишь в том, что здесь мы используем функцию open с оператором `with` – этим мы оставляем автоматическое закрытие файла под ответственность `with open`.  За кулисами происходит следующее. Существует некий протокол, используемый оператором with. Он считывает объект, возвращаемый оператором open. Назовём его в данном случае `«thefile»`.\n",
    "\n",
    "Перед запуском блока кода, содержащегося в нём, оператор `with` всегда вызывает функцию `thefile.__enter__`, а также всегда вызывает `thefile`. `__exit__` после завершения выполнения этого блока кода.\n",
    "\n",
    "Так что код, который мы бы написали в блоке `finally`, будет автоматически обработан методом `__exit__`. Это избавляет нас от необходимости повторно в явном виде указывать операторы `try..finally`. \n",
    "Более обширное рассмотрение этой темы выходит за рамки настоящей книги, поэтому для более исчерпывающего объяснения см. PEP 343. Мы обсудили использование операторов `try..except` и `try..finally`. Мы также увидели, как создавать наши собственные типы исключений и как их вызывать."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Полезные ссылки:**\n",
    "\n",
    "1. "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
